export const CONTENT_TYPES: { value: string, label: string, extensions: string[] }[] = [
  { value: 'audio/aac', label: 'audio/aac', extensions: ['.aac'] },
  { value: 'application/x-abiword', label: 'application/x-abiword', extensions: ['.abw'] },
  { value: 'image/apng', label: 'image/apng', extensions: ['.apng'] },
  { value: 'application/x-freearc', label: 'application/x-freearc', extensions: ['.arc'] },
  { value: 'image/avif', label: 'image/avif', extensions: ['.avif'] },
  { value: 'video/x-msvideo', label: 'video/x-msvideo', extensions: ['.avi'] },
  { value: 'application/vnd.amazon.ebook', label: 'application/vnd.amazon.ebook',
    extensions: ['.azw'] },
  { value: 'application/octet-stream', label: 'application/octet-stream', extensions: ['.bin'] },
  { value: 'image/bmp', label: 'image/bmp', extensions: ['.bmp'] },
  { value: 'application/x-bzip', label: 'application/x-bzip', extensions: ['.bz'] },
  { value: 'application/x-bzip2', label: 'application/x-bzip2', extensions: ['.bz2'] },
  { value: 'application/x-cdf', label: 'application/x-cdf', extensions: ['.cda'] },
  { value: 'application/x-csh', label: 'application/x-csh', extensions: ['.csh'] },
  { value: 'text/css', label: 'text/css', extensions: ['.css'] },
  { value: 'text/csv', label: 'text/csv', extensions: ['.csv'] },
  { value: 'application/msword', label: 'application/msword', extensions: ['.doc'] },
  { value: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    label: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    extensions: ['.docx'] },
  { value: 'application/vnd.ms-fontobject', label: 'application/vnd.ms-fontobject',
    extensions: ['.eot'] },
  { value: 'application/epub+zip', label: 'application/epub+zip', extensions: ['.epub'] },
  { value: 'application/x-gzip.', label: 'application/x-gzip.', extensions: ['.gz'] },
  { value: 'image/gif', label: 'image/gif', extensions: ['.gif'] },
  { value: 'text/html', label: 'text/html', extensions: ['.htm, .html'] },
  { value: 'image/vnd.microsoft.icon', label: 'image/vnd.microsoft.icon', extensions: ['.ico'] },
  { value: 'text/calendar', label: 'text/calendar', extensions: ['.ics'] },
  { value: 'application/java-archive', label: 'application/java-archive', extensions: ['.jar'] },
  { value: 'image/jpeg', label: 'image/jpeg', extensions: ['.jpeg, .jpg'] },
  { value: '9239)', label: '9239)', extensions: ['.js'] },
  { value: 'application/json', label: 'application/json', extensions: ['.json'] },
  { value: 'application/ld+json', label: 'application/ld+json', extensions: ['.jsonld'] },
  { value: 'audio/x-midi', label: 'audio/x-midi', extensions: ['.mid, .midi'] },
  { value: 'text/javascript', label: 'text/javascript', extensions: ['.mjs'] },
  { value: 'audio/mpeg', label: 'audio/mpeg', extensions: ['.mp3'] },
  { value: 'video/mp4', label: 'video/mp4', extensions: ['.mp4'] },
  { value: 'video/mpeg', label: 'video/mpeg', extensions: ['.mpeg'] },
  { value: 'application/vnd.apple.installer+xml', label: 'application/vnd.apple.installer+xml',
    extensions: ['.mpkg'] },
  { value: 'application/vnd.oasis.opendocument.presentation',
    label: 'application/vnd.oasis.opendocument.presentation', extensions: ['.odp'] },
  { value: 'application/vnd.oasis.opendocument.spreadsheet',
    label: 'application/vnd.oasis.opendocument.spreadsheet', extensions: ['.ods'] },
  { value: 'application/vnd.oasis.opendocument.text',
    label: 'application/vnd.oasis.opendocument.text', extensions: ['.odt'] },
  { value: 'video/ogg', label: 'video/ogg', extensions: ['.ogv'] },
  { value: 'application/ogg', label: 'application/ogg', extensions: ['.ogx'] },
  { value: 'audio/ogg', label: 'audio/ogg', extensions: ['.opus', '.oga'] },
  { value: 'font/otf', label: 'font/otf', extensions: ['.otf'] },
  { value: 'image/png', label: 'image/png', extensions: ['.png'] },
  { value: 'application/pdf', label: 'application/pdf', extensions: ['.pdf'] },
  { value: 'application/x-httpd-php', label: 'application/x-httpd-php', extensions: ['.php'] },
  { value: 'application/vnd.ms-powerpoint', label: 'application/vnd.ms-powerpoint',
    extensions: ['.ppt'] },
  { value: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    label: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    extensions: ['.pptx'] },
  { value: 'application/vnd.rar', label: 'application/vnd.rar', extensions: ['.rar'] },
  { value: 'application/rtf', label: 'application/rtf', extensions: ['.rtf'] },
  { value: 'application/x-sh', label: 'application/x-sh', extensions: ['.sh'] },
  { value: 'image/svg+xml', label: 'image/svg+xml', extensions: ['.svg'] },
  { value: 'application/x-tar', label: 'application/x-tar', extensions: ['.tar'] },
  { value: 'image/tiff', label: 'image/tiff', extensions: ['.tif, .tiff'] },
  { value: 'video/mp2t', label: 'video/mp2t', extensions: ['.ts'] },
  { value: 'font/ttf', label: 'font/ttf', extensions: ['.ttf'] },
  { value: 'text/plain', label: 'text/plain', extensions: ['.txt'] },
  { value: 'application/vnd.visio', label: 'application/vnd.visio', extensions: ['.vsd'] },
  { value: 'audio/wav', label: 'audio/wav', extensions: ['.wav'] },
  { value: 'audio/webm', label: 'audio/webm', extensions: ['.weba'] },
  { value: 'video/webm', label: 'video/webm', extensions: ['.webm'] },
  { value: 'image/webp', label: 'image/webp', extensions: ['.webp'] },
  { value: 'font/woff', label: 'font/woff', extensions: ['.woff'] },
  { value: 'font/woff2', label: 'font/woff2', extensions: ['.woff2'] },
  { value: 'application/xhtml+xml', label: 'application/xhtml+xml', extensions: ['.xhtml'] },
  { value: 'application/vnd.ms-excel', label: 'application/vnd.ms-excel', extensions: ['.xls'] },
  { value: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    label: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    extensions: ['.xlsx'] },
  { value: 'application/xml', label: 'application/xml', extensions: ['.xml'] },
  { value: 'text/xml', label: 'text/xml', extensions: ['.xml'] },
  { value: 'application/vnd.mozilla.xul+xml', label: 'application/vnd.mozilla.xul+xml',
    extensions: ['.xul'] },
  { value: 'application/x-zip-compressed.', label: 'application/x-zip-compressed.',
    extensions: ['.zip'] },
  { value: 'video/3gpp', label: 'video/3gpp', extensions: ['.3gp'] },
  { value: 'audio/3gpp', label: 'audio/3gpp', extensions: ['.3gp'] },
  { value: 'video/3gpp2', label: 'video/3gpp2', extensions: ['.3g2'] },
  { value: 'audio/3gpp2', label: 'audio/3gpp2', extensions: ['.3g2'] },
  { value: 'application/x-7z-compressed', label: 'application/x-7z-compressed',
    extensions: ['.7z'] },
]
